import {
  DEMO_AS_OF_DATE,
  DEMO_STATE_VERSION,
  type DemoState,
} from "./types";

/**
 * A fresh, deterministic state for demos and tests. Dates deliberately use the
 * product's frozen visual-test clock instead of the browser clock.
 */
export function createDemoState(): DemoState {
  return {
    version: DEMO_STATE_VERSION,
    asOfDate: DEMO_AS_OF_DATE,
    user: {
      id: "employee-anna-smirnova",
      fullName: "Анна Смирнова",
      firstName: "Анна",
      initials: "АС",
      role: "Аналитик",
      grade: "G7",
      department: "Цифровая трансформация",
      location: "Алматы",
      level: 8,
      totalXp: 7_240,
      streakDays: 14,
      visibility: {
        profile: "company",
        skills: "team",
        achievements: "company",
      },
    },
    goal: {
      role: "Руководитель проекта",
      grade: "G8",
      targetDate: "2027-03-31",
      reason: "Хочу вести кросс-функциональные инициативы и отвечать за результат",
    },
    careerNodes: [
      {
        id: "career-junior-analyst",
        title: "Младший аналитик",
        grade: "G6",
        status: "completed",
        parentIds: [],
        requirement: "Базовые навыки анализа данных",
      },
      {
        id: "career-analyst",
        title: "Аналитик",
        grade: "G7",
        status: "current",
        parentIds: ["career-junior-analyst"],
        requirement: "Подтверждена текущая роль",
      },
      {
        id: "career-project-manager",
        title: "Руководитель проекта",
        grade: "G8",
        status: "available",
        parentIds: ["career-analyst"],
        requirement: "Готовность 85% и завершённый лидерский квест",
      },
      {
        id: "career-product-owner",
        title: "Product Owner",
        grade: "G8",
        status: "available",
        parentIds: ["career-analyst"],
        requirement: "Навык Agile не ниже 3",
      },
      {
        id: "career-program-director",
        title: "Директор программ",
        grade: "G10",
        status: "locked",
        parentIds: ["career-project-manager"],
        requirement: "Опыт руководства проектами от 2 лет",
      },
    ],
    skills: [
      {
        id: "skill-analytics",
        name: "Анализ данных",
        category: "digital",
        currentLevel: 4,
        targetLevel: 4,
        maxLevel: 5,
        readinessWeight: 1,
        status: "mastered",
        relatedSkillIds: ["skill-strategy"],
        evidence: [
          {
            id: "evidence-analytics-dashboard",
            title: "Дашборд по эффективности",
            kind: "artifact",
            verified: true,
            earnedAt: "2026-05-18",
          },
        ],
      },
      {
        id: "skill-project-management",
        name: "Управление проектами",
        category: "professional",
        currentLevel: 3,
        targetLevel: 5,
        maxLevel: 5,
        readinessWeight: 1.5,
        status: "developing",
        relatedSkillIds: ["skill-leadership", "skill-agile"],
        evidence: [
          {
            id: "evidence-pm-feedback",
            title: "Feedback от куратора пилота",
            kind: "feedback",
            verified: true,
            earnedAt: "2026-08-29",
          },
        ],
      },
      {
        id: "skill-leadership",
        name: "Лидерство",
        category: "leadership",
        currentLevel: 2,
        targetLevel: 4,
        maxLevel: 5,
        readinessWeight: 1.4,
        status: "developing",
        relatedSkillIds: ["skill-communication", "skill-project-management"],
        evidence: [],
      },
      {
        id: "skill-strategy",
        name: "Стратегическое мышление",
        category: "business",
        currentLevel: 3,
        targetLevel: 4,
        maxLevel: 5,
        readinessWeight: 1.3,
        status: "developing",
        relatedSkillIds: ["skill-analytics", "skill-project-management"],
        evidence: [],
      },
      {
        id: "skill-communication",
        name: "Коммуникация",
        category: "leadership",
        currentLevel: 4,
        targetLevel: 4,
        maxLevel: 5,
        readinessWeight: 1,
        status: "mastered",
        relatedSkillIds: ["skill-leadership"],
        evidence: [
          {
            id: "evidence-presentations-certificate",
            title: "Влиятельные презентации",
            kind: "certificate",
            verified: true,
            earnedAt: "2026-07-12",
          },
        ],
      },
      {
        id: "skill-agile",
        name: "Agile и Scrum",
        category: "professional",
        currentLevel: 2,
        targetLevel: 3,
        maxLevel: 5,
        readinessWeight: 0.8,
        status: "developing",
        relatedSkillIds: ["skill-project-management"],
        evidence: [],
      },
    ],
    quests: [
      {
        id: "quest-lead-pilot",
        title: "Возглавь пилотный проект",
        description: "Собери команду, проведи пилот и защити результат",
        kind: "career",
        difficulty: "hard",
        status: "active",
        dueDate: "2026-10-24",
        xpReward: 600,
        skillIds: ["skill-project-management", "skill-leadership"],
        skillGain: { skillId: "skill-project-management", levels: 1 },
        progressPercent: 60,
        evidence: [
          {
            id: "proof-pilot-charter",
            label: "Утверждён чартер проекта",
            completed: true,
            weight: 30,
            completedAt: "2026-09-05",
          },
          {
            id: "proof-pilot-team",
            label: "Сформирована команда",
            completed: true,
            weight: 30,
            completedAt: "2026-09-12",
          },
          {
            id: "proof-pilot-demo",
            label: "Проведена защита результата",
            completed: false,
            weight: 40,
          },
        ],
        isPrimary: true,
      },
      {
        id: "quest-stakeholder-feedback",
        title: "Собери feedback стейкхолдеров",
        description: "Проведи три коротких интервью и выдели точки роста",
        kind: "practice",
        difficulty: "easy",
        status: "active",
        dueDate: "2026-09-18",
        xpReward: 180,
        skillIds: ["skill-communication"],
        progressPercent: 33,
        evidence: [
          { id: "proof-feedback-1", label: "Интервью 1", completed: true, weight: 33, completedAt: "2026-09-10" },
          { id: "proof-feedback-2", label: "Интервью 2", completed: false, weight: 33 },
          { id: "proof-feedback-3", label: "Интервью 3", completed: false, weight: 34 },
        ],
        isPrimary: false,
      },
      {
        id: "quest-strategy-case",
        title: "Разбери стратегический кейс",
        description: "Предложи решение для нового цифрового продукта",
        kind: "learning",
        difficulty: "medium",
        status: "available",
        dueDate: "2026-11-15",
        xpReward: 320,
        skillIds: ["skill-strategy"],
        skillGain: { skillId: "skill-strategy", levels: 1 },
        progressPercent: 0,
        evidence: [
          { id: "proof-strategy-case", label: "Загружена записка с решением", completed: false, weight: 100 },
        ],
        isPrimary: false,
      },
      {
        id: "quest-agile-facilitation",
        title: "Проведи ретроспективу",
        description: "Сфасилитируй встречу команды и зафиксируй action items",
        kind: "team",
        difficulty: "medium",
        status: "available",
        dueDate: "2026-10-10",
        xpReward: 250,
        skillIds: ["skill-agile", "skill-leadership"],
        progressPercent: 0,
        evidence: [
          { id: "proof-retro-notes", label: "Опубликованы итоги", completed: false, weight: 100 },
        ],
        isPrimary: false,
      },
      ...[
        ["quest-complete-dashboard", "Создай дашборд для бизнеса", "skill-analytics", 280, "2026-05-18"],
        ["quest-complete-presentation", "Защити аналитическую гипотезу", "skill-communication", 220, "2026-06-02"],
        ["quest-complete-course", "Пройди курс по презентациям", "skill-communication", 180, "2026-07-12"],
        ["quest-complete-shadowing", "Пройди shadowing руководителя", "skill-leadership", 260, "2026-08-01"],
        ["quest-complete-planning", "Составь план мини-проекта", "skill-project-management", 300, "2026-08-22"],
      ].map(([id, title, skillId, reward, completedAt]) => ({
        id: id as string,
        title: title as string,
        description: "Завершённый шаг к карьерной цели",
        kind: "practice" as const,
        difficulty: "medium" as const,
        status: "completed" as const,
        dueDate: completedAt as `${number}-${number}-${number}`,
        xpReward: reward as number,
        skillIds: [skillId as string],
        progressPercent: 100,
        evidence: [
          {
            id: `proof-${id as string}`,
            label: "Доказательство принято",
            completed: true,
            weight: 100,
            completedAt: completedAt as `${number}-${number}-${number}`,
          },
        ],
        isPrimary: false,
      })),
    ],
    learning: [
      {
        id: "learning-strategic-thinking",
        title: "Стратегическое мышление",
        provider: "Halyk Academy",
        description: "Инструменты для решения сложных бизнес-задач",
        format: "course",
        durationMinutes: 360,
        status: "in_progress",
        progressPercent: 68,
        skillIds: ["skill-strategy"],
        saved: true,
        readinessImpact: 8,
      },
      {
        id: "learning-project-leadership",
        title: "Лидерство в проектной команде",
        provider: "Halyk Academy",
        description: "Практикум по ситуационному лидерству",
        format: "workshop",
        durationMinutes: 240,
        status: "recommended",
        progressPercent: 0,
        skillIds: ["skill-leadership", "skill-project-management"],
        saved: false,
        nextSessionAt: "2026-09-29T10:00:00+05:00",
        readinessImpact: 7,
      },
      {
        id: "learning-agile",
        title: "Agile-практики для команд",
        provider: "Qaldy Learning",
        description: "Scrum, Kanban и фасилитация командных ритуалов",
        format: "course",
        durationMinutes: 180,
        status: "recommended",
        progressPercent: 0,
        skillIds: ["skill-agile"],
        saved: true,
        readinessImpact: 5,
      },
      {
        id: "learning-presentations",
        title: "Влиятельные презентации",
        provider: "Halyk Academy",
        description: "Структура и подача бизнес-истории",
        format: "course",
        durationMinutes: 120,
        status: "completed",
        progressPercent: 100,
        skillIds: ["skill-communication"],
        saved: false,
        readinessImpact: 3,
      },
    ],
    certificates: [
      {
        id: "certificate-learning-presentations",
        sourceLearningId: "learning-presentations",
        title: "Влиятельные презентации",
        issuer: "Halyk Academy",
        issuedAt: "2026-07-12",
      },
    ],
    opportunities: [
      {
        id: "opportunity-pm-assistant",
        title: "Ассистент руководителя проекта",
        description: "Роль в стратегической цифровой инициативе",
        kind: "project",
        department: "Цифровая трансформация",
        location: "Алматы",
        matchPercent: 92,
        skillIds: ["skill-project-management", "skill-leadership"],
        deadline: "2026-10-02",
        saved: true,
        applied: false,
      },
      {
        id: "opportunity-pm-vacancy",
        title: "Руководитель проекта",
        description: "Внутренняя вакансия в команде развития продуктов",
        kind: "vacancy",
        department: "Развитие продуктов",
        location: "Гибридно",
        matchPercent: 78,
        skillIds: ["skill-project-management", "skill-strategy"],
        deadline: "2026-10-12",
        saved: false,
        applied: false,
      },
      {
        id: "opportunity-mentor-aigerim",
        title: "Менторская сессия с директором программ",
        description: "45 минут о переходе в проектное управление",
        kind: "mentoring",
        department: "Офис трансформации",
        location: "Online",
        matchPercent: 88,
        skillIds: ["skill-leadership"],
        saved: false,
        applied: true,
      },
      {
        id: "opportunity-rotation-product",
        title: "Ротация в продуктовую команду",
        description: "Три месяца практики в Product Discovery",
        kind: "rotation",
        department: "Digital Products",
        location: "Алматы",
        matchPercent: 74,
        skillIds: ["skill-agile", "skill-strategy"],
        deadline: "2026-11-01",
        saved: false,
        applied: false,
      },
    ],
    teamMission: {
      id: "mission-customer-onboarding",
      title: "Ускорить onboarding клиентов",
      description: "Сократить время прохождения цифрового onboarding на 20%",
      role: "Аналитик и координатор",
      progressPercent: 54,
      dueDate: "2026-10-24",
      linkedQuestId: "quest-lead-pilot",
      members: [
        { id: "team-anna", name: "Анна Смирнова", initials: "АС", publicRole: "Координатор", contribution: "Метрики и план" },
        { id: "team-daniyar", name: "Данияр К.", initials: "ДК", publicRole: "Product Owner", contribution: "Приоритеты" },
        { id: "team-aida", name: "Аида Т.", initials: "АТ", publicRole: "UX-исследователь", contribution: "Интервью" },
        { id: "team-ruslan", name: "Руслан М.", initials: "РМ", publicRole: "Tech Lead", contribution: "Прототип" },
      ],
      helpRequests: [
        { id: "help-facilitation", title: "Нужен совет по фасилитации demo", skillId: "skill-leadership", authorName: "Анна", status: "open" },
        { id: "help-metrics", title: "Какую метрику взять главной?", skillId: "skill-analytics", authorName: "Аида", status: "answered" },
      ],
    },
    library: [
      {
        id: "resource-project-charter",
        title: "Шаблон чартера проекта",
        description: "Готовая структура для целей, границ и рисков",
        author: "Halyk PMO",
        kind: "template",
        durationMinutes: 10,
        tags: ["проект", "шаблон"],
        skillIds: ["skill-project-management"],
        saved: true,
        lastViewedAt: "2026-09-22T15:10:00+05:00",
      },
      {
        id: "resource-strategy-article",
        title: "Пять уровней стратегии",
        description: "Как связать цели компании с решениями команды",
        author: "Айгерим Нурланова",
        kind: "article",
        durationMinutes: 14,
        tags: ["стратегия", "лидерство"],
        skillIds: ["skill-strategy"],
        saved: true,
        lastViewedAt: "2026-09-21T09:30:00+05:00",
      },
      {
        id: "resource-feedback-video",
        title: "Обратная связь без напряжения",
        description: "Разбор модели SBI на рабочих примерах",
        author: "Qaldy Learning",
        kind: "video",
        durationMinutes: 18,
        tags: ["feedback", "коммуникация"],
        skillIds: ["skill-communication", "skill-leadership"],
        saved: false,
        lastViewedAt: "2026-09-18T13:00:00+05:00",
      },
      {
        id: "resource-pm-book",
        title: "Управление проектами: практический гайд",
        description: "Короткое руководство по планированию и контролю",
        author: "Halyk PMO",
        kind: "book",
        durationMinutes: 95,
        tags: ["проект", "планирование"],
        skillIds: ["skill-project-management"],
        saved: false,
      },
    ],
    achievements: [
      { id: "achievement-first-quest", title: "Первый квест", description: "Завершён первый карьерный квест", earnedAt: "2026-05-18", icon: "star", xpAwarded: 100 },
      { id: "achievement-data-storyteller", title: "Data Storyteller", description: "Аналитическая история убедила стейкхолдеров", earnedAt: "2026-06-02", icon: "sparkles", xpAwarded: 150 },
      { id: "achievement-five-quests", title: "Пять побед", description: "Завершено 5 квестов", earnedAt: "2026-08-22", icon: "trophy", xpAwarded: 250 },
    ],
    portfolio: [
      { id: "portfolio-dashboard", title: "Дашборд по эффективности", description: "Метрики и визуализация для бизнес-команды", kind: "project", createdAt: "2026-05-18" },
      { id: "portfolio-pilot-charter", title: "Чартер onboarding-пилота", description: "Цели, границы, команда и риски", kind: "document", createdAt: "2026-09-05" },
    ],
    aiMessages: [
      {
        id: "ai-message-welcome",
        role: "assistant",
        content: "Анна, я проанализировал вашу цель. Главная точка роста — лидерство в проектах. Ниже собрал план на ближайшие 90 дней.",
        createdAt: "2026-09-23T09:00:00+05:00",
        sources: [
          { id: "source-leadership", title: "Разрыв по лидерству", kind: "skill", entityId: "skill-leadership" },
          { id: "source-pilot", title: "Пилотный проект", kind: "quest", entityId: "quest-lead-pilot" },
        ],
      },
    ],
    aiPlan: {
      title: "План перехода к роли руководителя проекта",
      summary: "Закройте лидерский квест, дойдите курс и получите feedback от куратора",
      projectedReadinessImpact: 12,
      impactExplanation: "Эффекты +8%, +7% и +5% пересекаются по одним и тем же компетенциям; прогноз ограничен +12%, а не суммируется до +20%.",
      steps: [
        { id: "plan-course", title: "Завершить курс", description: "Дойти оставшиеся 32% курса", status: "current", entityId: "learning-strategic-thinking" },
        { id: "plan-pilot", title: "Защитить пилот", description: "Приложить финальную презентацию", status: "next", entityId: "quest-lead-pilot" },
        { id: "plan-feedback", title: "Запросить feedback", description: "Получить оценку от куратора и команды", status: "next", entityId: "quest-stakeholder-feedback" },
      ],
      alternativeRoute: {
        title: "Маршрут Product Owner",
        description: "Усилить Agile и пройти ротацию в продуктовой команде",
        entityIds: ["career-product-owner", "learning-agile", "opportunity-rotation-product"],
      },
    },
    selectedTabs: {
      quests: "all",
      learning: "recommended",
      opportunities: "all",
      library: "all",
    },
  };
}

export const demoFixture = createDemoState();
